class Locators:
    username_xpath = "//input[@id='user-name']"
    password_xpath = "//input[@id='password']"
    login_btn_xpath = "//input[@type='submit']"
    items_price = "inventory_item_price"
    add_to_cart = "//button[contains(@id,'add-to-cart')]"
    items_name = "inventory_item_name"
    inventory_page_title="//span[@class='title']"
    cart_page_badge="//span[@class='shopping_cart_badge']"
    filter_low_high="//option[@value='lohi']"
    shopping_cart_link = "//a[@class='shopping_cart_link']"
    remove_btn_path = "//button[contains(@id,'remove')]"
    checkout_btn_path = "//button[contains(@id,'checkout')]"
    continue_btn_path="//button[@id='continue-shopping']"
    firstname_path = "//input[@id='first-name']"
    lastname_path = "//input[@id='last-name']"
    postal_code = "//input[@id='postal-code']"
    continue_btn = "//input[@id='continue']"
    finish_btn = "//button[@id='finish']"
    message_heading = "//h2"
